services:
  postgres:
    image: ankane/pgvector
    container_name: postgres-youtube
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: n8n
      POSTGRES_USER: postgres
    networks:
      - n8n-queue

  redis:
    image: redis:alpine
    container_name: redis-queue
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    networks:
      - n8n-queue
    restart: always

  n8n-editor:
    image: n8nio/n8n:latest
    container_name: n8n-editor
    ports:
      - 5678:5678
    networks:
      - n8n-queue
    restart: unless-stopped
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  n8n-worker:
    image: n8nio/n8n:latest
    container_name: n8n-worker
    ports:
      - 5679:5678
    networks:
      - n8n-queue
    restart: unless-stopped
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: worker

  n8n-webhooks:
    image: n8nio/n8n:latest
    container_name: n8n-webhooks
    ports:
      - 5680:5678
    networks:
      - n8n-queue
    restart: unless-stopped
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: webhooks

networks:
  n8n-queue:
    driver: bridge
